# model/tokenizer
model_name: "zpn/llama-7b" # update
tokenizer_name: "LlamaTokenizer" # update
gradient_checkpointing: false
save_name: "tella/gpt4all-lora"

# dataset
streaming: false
num_proc: 64
dataset_path: "data_multiturn"
max_length: 1024
batch_size: 4

# train dynamics
lr: 5.0e-5
eval_every: 2000
eval_steps: 100
save_every: 2000
output_dir: "ckpts/gpt4all-lora-multi"
checkpoint: null
lora: true
warmup_steps: 100
num_epochs: 2

# logging
wandb: true
wandb_entity: # update
wandb_project_name: "Tella_GPT4" # update
seed: 42
