# model/tokenizer
model_name: "Tella/gpt4all" # add model here
tokenizer_name: "Tella/gpt4all" # add model here
gradient_checkpointing: true
save_name: "tella/gpt4all-full"

# dataset
streaming: false
num_proc: 64
dataset_path: # update
max_length: 1024
batch_size: 32

# train dynamics
lr: 5.0e-5
eval_every: 800
eval_steps: 100
save_every: 800
output_dir: "ckpts/gpt4all-full-multi"
checkpoint: null
lora: false
warmup_steps: 100
num_epochs: 2

# logging
wandb: true
wandb_entity: # update
wandb_project_name: GPT4-tella # update
seed: 42

